### ISSUE TITLE
Caption displaying along with zoomed image?

### ISSUE THREAD

**Issue by justinclift** [arp242/imgzoom#1]
Looking at imgzoom as a potential replacement for the old AngularJS (v1!) based lightbox being used on a website currently.

The only important thing it's really missing, is some way to display a caption along with the zoomed image.  Like a text string below or above the image - similar to the `<figcaption>` tag - but only displaying in the pop-up not in the main page text.

Is that kind of thing likely to be added at some point? :smile:

**Comment by arp242** [comment]
I don't think this is something that's very to add, because now there's the assumption that you're always dealing with an `<img>`, and getting the size calculations correct is a lot trickier when you add font metrics. It would need more CSS as well.

Captions can definitely be useful in some cases, but generally speaking I find you need it less often than you'd think. I wouldn't mind adding it if it would be a simple change, but not sure if it's worth supporting here given the added complexity: I rather like the simplicity and easy-of-use of the current version.

**Comment by justinclift** [comment]
Makes sense. :smile:
